// Maps common destination search terms to IATA codes.
// Used to expand flight search results — e.g. "Tenerife" matches TFS and TFN.
export const DESTINATION_ALIASES: Record<string, string[]> = {
  'tenerife':        ['TFS', 'TFN'],
  'lanzarote':       ['ACE'],
  'fuerteventura':   ['FUE'],
  'gran canaria':    ['LPA'],
  'majorca':         ['PMI'],
  'mallorca':        ['PMI'],
  'ibiza':           ['IBZ'],
  'menorca':         ['MAH'],
  'canary islands':  ['TFS', 'TFN', 'ACE', 'FUE', 'LPA'],
  'balearics':       ['PMI', 'IBZ', 'MAH'],
  'corfu':           ['CFU'],
  'rhodes':          ['RHO'],
  'crete':           ['HER', 'CHQ'],
  'heraklion':       ['HER'],
  'chania':          ['CHQ'],
  'zante':           ['ZTH'],
  'zakynthos':       ['ZTH'],
  'kos':             ['KGS'],
  'santorini':       ['JTR'],
  'mykonos':         ['JMK'],
  'kefalonia':       ['EFL'],
  'skiathos':        ['JSI'],
  'greek islands':   ['RHO', 'CFU', 'HER', 'CHQ', 'ZTH', 'KGS', 'JTR', 'JMK'],
  'cyprus':          ['PFO', 'LCA'],
  'paphos':          ['PFO'],
  'larnaca':         ['LCA'],
  'turkey':          ['AYT', 'DLM', 'BJV', 'ADB'],
  'antalya':         ['AYT'],
  'dalaman':         ['DLM'],
  'bodrum':          ['BJV'],
  'izmir':           ['ADB'],
  'algarve':         ['FAO'],
  'faro':            ['FAO'],
  'lisbon':          ['LIS'],
  'porto':           ['OPO'],
  'madeira':         ['FNC'],
  'azores':          ['PDL', 'TER'],
  'barcelona':       ['BCN'],
  'madrid':          ['MAD'],
  'malaga':          ['AGP'],
  'costa del sol':   ['AGP'],
  'benidorm':        ['ALC'],
  'alicante':        ['ALC'],
  'valencia':        ['VLC'],
  'seville':         ['SVQ'],
  'bilbao':          ['BIO'],
  'paris':           ['CDG', 'ORY'],
  'nice':            ['NCE'],
  'amsterdam':       ['AMS'],
  'rome':            ['FCO', 'CIA'],
  'milan':           ['MXP', 'LIN', 'BGY'],
  'venice':          ['VCE'],
  'florence':        ['FLR'],
  'naples':          ['NAP'],
  'sicily':          ['CTA', 'PMO'],
  'sardinia':        ['CAG', 'OLB'],
  'brussels':        ['BRU'],
  'frankfurt':       ['FRA'],
  'berlin':          ['BER'],
  'munich':          ['MUC'],
  'vienna':          ['VIE'],
  'prague':          ['PRG'],
  'budapest':        ['BUD'],
  'krakow':          ['KRK'],
  'warsaw':          ['WAW'],
  'dubrovnik':       ['DBV'],
  'split':           ['SPU'],
  'croatia':         ['DBV', 'SPU', 'ZAD'],
  'bucharest':       ['OTP'],
  'sofia':           ['SOF'],
  'athens':          ['ATH'],
  'thessaloniki':    ['SKG'],
  'istanbul':        ['IST', 'SAW'],
  'marrakech':       ['RAK'],
  'cairo':           ['CAI'],
  'hurghada':        ['HRG'],
  'sharm el sheikh': ['SSH'],
  'egypt':           ['HRG', 'SSH', 'CAI'],
  'tunis':           ['TUN'],
  'dubai':           ['DXB'],
  'abu dhabi':       ['AUH'],
  'doha':            ['DOH'],
  'maldives':        ['MLE'],
  'bali':            ['DPS'],
  'phuket':          ['HKT'],
  'bangkok':         ['BKK'],
  'thailand':        ['BKK', 'HKT', 'USM'],
  'singapore':       ['SIN'],
  'hong kong':       ['HKG'],
  'tokyo':           ['NRT', 'HND'],
  'sri lanka':       ['CMB'],
  'florida':         ['MCO', 'MIA', 'TPA', 'FLL'],
  'orlando':         ['MCO'],
  'miami':           ['MIA'],
  'new york':        ['JFK', 'EWR', 'LGA'],
  'los angeles':     ['LAX'],
  'san francisco':   ['SFO'],
  'chicago':         ['ORD', 'MDW'],
  'cancun':          ['CUN'],
  'mexico':          ['MEX', 'CUN'],
  'toronto':         ['YYZ'],
  'vancouver':       ['YVR'],
  'sydney':          ['SYD'],
  'melbourne':       ['MEL'],
  'australia':       ['SYD', 'MEL', 'BNE'],
  'johannesburg':    ['JNB'],
  'cape town':       ['CPT'],
  'south africa':    ['JNB', 'CPT'],
}

export function matchAliases(query: string): string[] {
  const q = query.toLowerCase()
  const iatas = new Set<string>()
  for (const [alias, codes] of Object.entries(DESTINATION_ALIASES)) {
    if (alias.includes(q) || q.includes(alias)) {
      codes.forEach(c => iatas.add(c))
    }
  }
  return [...iatas]
}
